Ext.define('Beerhere.view.BeerCntr', {
    extend: 'Ext.Container',
    xtype: 'beercntr',

    cls: 'beerCntr',

    html: `
    Jim Pedersen, der døde i marts 2017.</p><p>- Han bad mig om at hive pengene hjem fra Tankoil. Det var 110 mio. dollars. Det vidste jeg, at de ikke kunne betale på en gang, og det fortalte jeg ledelsen.</p><h3>Fik frataget sit pas</h3><p>Herefter blev Lars Møller bortvist fra sit job ligesom Kimmie Goh, og de oplevede begge at få frataget deres pas.</p><p>- De mente, at det var vores skyld, at vi havde udestående med Tankoil, og at vi ikke kunne få pengene hjem, huskede Lars Møller.</p><p class="linkbox"><span>Læs også: </span><a href="/nyheder/penge/ow-bunker-direktoer-tiltalt-give-giga-kredit-i-dag-begynder-retssagen">OW Bunker-direktør tiltalt for at give giga-kredit: I dag begynder retssagen</a></p><p>Så langt er Lars Møller stort set enig med de forklaringer, som nu afdøde Jim Pedersen og flere andre ledende medarbejdere er kommet med.</p><p>Lars Møller kan imidlertid ikke genkende de tidligere kollegers beskrivelse af, at han tilstod at han havde skjult størrelsen på kreditten til Tankoil. Akkurat som han er rasende over, at en kollega havde forfattet en mail til Jim Pedersen, hvor han skrev, at Lars Møller havde overvejet selvmord kort efter, at han var blevet bortvist.</p><h3>Angriber kollega</h3><p>- Det er absurd, at jeg skulle tage livet af mig selv. Og det er helt forkert, at jeg skulle have sagt, at jeg gemte kreditter for 100 mio. kr. i systemet. Jeg synes, at den mailkorrespondance er meget mistænkelig, for at sige det mildt, sagde Lars Møller og pegede blandt andet på, at mailen var skrevet 19 dage efter den dramatiske nat.</p><p>Lars Møller antydede også, at Jim Pedersen i dagene op til konkursen forsøgte at skabe sig et alibi ved pludselig at sende detaljerede sms-beskeder, selv om han normalt plejede at ordne vigtige ting over telefonen.</p><p>- Det er måske ikke helt tilfældigt, at der nu bliver sendt noget på skrift på det her tidspunkt. Det kunne være, at han havde en forventning om, at OW kunne komme i problemer, sagde Lars Møller.</p><p class="linkbox"><span>Læs også: </span><a href="/nyheder/penge/ow-bunker-investorer-staevner-morgan-stanley-og-carnegie">OW Bunker-investorer stævner Morgan Stanley og Carnegie</a></p><p>I sms-korrespondancen med Jim Pedersen havde Lars Møller skrevet, at Tankoils nettogæld til DOT var på fire mio. USD. Han forstod derfor godt, hvorfor specialanklageren undrede sig over, at den reelle gæld få dage senere var vokset til 110 mio. USD.</p><p>Lars Møller kunne ikke forklare, hvordan
    ` 
});
